#!/bin/bash
# My first script Run this within the installation directory.

echo "start install!"
mkdir gst-home
cd gst-home
sudo apt-get install build-essential

wget ftp://sourceware.org/pub/libffi/libffi-3.2.1.tar.gz
tar xvf libffi-3.2.1.tar.gz
cd libffi-3.2.1
./configure
make -j16
sudo make install
cd ..

# setup other stuff.
sudo apt-get install zlib1g-dev

wget http://pkgconfig.freedesktop.org/releases/pkg-config-0.29.tar.gz
tar xvf pkg-config-0.29.tar.gz
cd pkg-config-0.29
./configure --with-internal-glib
make -j16
sudo make install
cd ..

wget http://ftp.gnu.org/pub/gnu/gettext/gettext-0.19.5.tar.gz
tar xvf gettext-0.19.5.tar.gz
cd gettext-0.19.5
./configure
make -j16
sudo make install
cd ..

wget http://ftp.gnome.org/pub/gnome/sources/glib/2.46/glib-2.46.0.tar.xz
tar xvf glib-2.46.0.tar.xz
cd glib-2.46.0
./configure
make -j16
sudo make install
cd ..

sudo apt-get install bison flex -y

wget http://gstreamer.freedesktop.org/src/gstreamer/gstreamer-1.6.0.tar.xz
tar xvf gstreamer-1.6.0.tar.xz
cd gstreamer-1.6.0
./configure
make -j16
sudo make install
cd ..

# libs for flitesrc
# Reinstall pkg-config with updated glib.
cd pkg-config-0.29
./configure
make -j16
sudo make install
cd ..

wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
tar xvf autoconf-2.69.tar.gz
cd autoconf-2.69
./configure
make -j16
sudo make install
cd ..

wget ftp://ftp.gnu.org/gnu/automake/automake-1.15.tar.gz
tar xvf automake-1.15.tar.gz
cd automake-1.15
./configure
make -j16
sudo make install
cd ..

wget http://gnu.mirror.iweb.com/libtool/libtool-2.4.6.tar.gz
tar xvf libtool-2.4.6.tar.gz
cd libtool-2.4.6
./configure
make -j16
sudo make install
cd ..

# Orc acceleration
wget http://gstreamer.freedesktop.org/src/orc/orc-0.4.24.tar.xz
tar xvf orc-0.4.19.tar.gz
cd orc-0.4.19
./configure
make -j16
sudo make install
cd ..

# optional base plugins. good to have.
wget http://alsa.cybermirror.org/lib/alsa-lib-1.0.29.tar.bz2
tar xvf alsa-lib-1.0.29.tar.bz2
cd alsa-lib-1.0.29
./configure
make -j16
sudo make install
cd ..

wget http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.xz
tar xvf libogg-1.3.2.tar.xz
cd libogg-1.3.2
./configure
make -j16
sudo make install
cd ..

wget http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.5.tar.gz
tar xvf libvorbis-1.3.5.tar.gz
cd libvorbis-1.3.5
./configure
make -j16
sudo make install
cd ..

wget http://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2
tar xvf libtheora-1.1.1.tar.bz2
cd libtheora-1.1.1
./configure
make -j16
sudo make install
cd ..

wget http://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-1.6.0.tar.xz
tar xvf gst-plugins-base-1.6.0.tar.xz
cd gst-plugins-base-1.6.0
./configure
make -j16
sudo make install
cd ..

# libav
sudo apt-get install yasm
wget http://gstreamer.freedesktop.org/src/gst-libav/gst-libav-1.6.0.tar.xz
tar xvf gst-libav-1.6.0.tar.xz
cd gst-libav-1.6.0
./configure
make -j16
sudo make install
cd ..

# good plugins
wget http://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-1.6.0.tar.xz
tar xvf gst-plugins-good-1.6.0.tar.xz
cd gst-plugins-good-1.6.0
./configure
make -j16
sudo make install
cd ..

wget http://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-1.6.0.tar.xz
tar xvf gst-plugins-bad-1.6.0.tar.xz
cd gst-plugins-bad-1.6.0
./configure
make -j16
sudo make install
cd ..

wget http://sourceforge.net/projects/opencore-amr/files/opencore-amr/opencore-amr-0.1.3.tar.gz
tar xvf opencore-amr-0.1.3.tar.gz
cd opencore-amr-0.1.3
./configure
make -j16
sudo make install
cd ..

wget http://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-1.6.0.tar.xz
tar xvf gst-plugins-ugly-1.6.0.tar.xz
cd gst-plugins-ugly-1.6.0
./configure
make -j16
sudo make install
cd ..

mkdir flitevox
mkdir gen-files

git clone https://github.com/theconsummate/gst-rtsp-server.git
cd gst-rtsp-server
./configure
make -j16
sudo make install
cd ..



echo "end"
